FROM payara/micro:6.2023.10-jdk17

HEALTHCHECK --start-period=5s --interval=5s --timeout=1s --retries=2 CMD wget -q --spider http://localhost:8080/health || exit 1

ARG JAKARTA_PERSISTENCE_JDBC_DRIVER=oracle.jdbc.OracleDriver
ENV JAKARTA_PERSISTENCE_JDBC_DRIVER=${JAKARTA_PERSISTENCE_JDBC_DRIVER:-oracle.jdbc.OracleDriver}

ARG JAKARTA_PERSISTENCE_JDBC_URL=jdbc:oracle:thin:HALCYON_APP_PROXY1[HALCYON_APP]/p455w0Rd@//host.docker.internal:1521/FREEPDB1
ENV JAKARTA_PERSISTENCE_JDBC_URL=${JAKARTA_PERSISTENCE_JDBC_URL:-host.docker.internal}

ARG JAKARTA_PERSISTENCE_JDBC_USER=HALCYON_APP_PROXY1[HALCYON_APP]
ENV JAKARTA_PERSISTENCE_JDBC_USER=${JAKARTA_PERSISTENCE_JDBC_USER:-HALCYON_APP_PROXY1[HALCYON_APP]}

ARG JAKARTA_PERSISTENCE_JDBC_PASSWORD=p455w0Rd
ENV JAKARTA_PERSISTENCE_JDBC_PASSWORD=${JAKARTA_PERSISTENCE_JDBC_PASSWORD:-p455w0Rd}

ARG JAKARTA_PERSISTENCE_SQL_LOAD_SCRIPT_SOURCE=
ENV JAKARTA_PERSISTENCE_SQL_LOAD_SCRIPT_SOURCE=${JAKARTA_PERSISTENCE_SQL_LOAD_SCRIPT_SOURCE:-}

ARG JAKARTA_PERSISTENCE_SCHEMA_GENERATION_DATABASE_ACTION=none
ENV JAKARTA_PERSISTENCE_SCHEMA_GENERATION_DATABASE_ACTION=${JAKARTA_PERSISTENCE_SCHEMA_GENERATION_DATABASE_ACTION:-none}

COPY ./target/ROOT.war $DEPLOY_DIR
