USE [master];

-- ALTER LOGIN [MICROSERVICE_ADMIN] DISABLE;
-- ALTER LOGIN [MICROSERVICE_ADMIN_PROXY1] DISABLE;
-- ALTER LOGIN [MICROSERVICE_ADMIN_PROXY2] DISABLE;
-- -- ALTER LOGIN [MICROSERVICE] DISABLE;
-- ALTER LOGIN [MICROSERVICE_PROXY1] DISABLE;
-- ALTER LOGIN [MICROSERVICE_PROXY2] DISABLE;
-- ALTER LOGIN [MICROSERVICE_READER] DISABLE;
-- DROP SCHEMA [MICROSERVICE];
-- DROP LOGIN [MICROSERVICE_ADMIN];
-- DROP LOGIN [MICROSERVICE_ADMIN_PROXY1];
-- DROP LOGIN [MICROSERVICE_ADMIN_PROXY2];
-- -- DROP LOGIN [MICROSERVICE];
-- DROP LOGIN [MICROSERVICE_PROXY1];
-- DROP LOGIN [MICROSERVICE_PROXY2];
-- DROP LOGIN [MICROSERVICE_READER];

-- Create users
CREATE LOGIN [MICROSERVICE_ADMIN] WITH PASSWORD=N'p455w0Rd', DEFAULT_DATABASE=[master], DEFAULT_LANGUAGE=[us_english], CHECK_EXPIRATION=OFF, CHECK_POLICY=ON;

CREATE USER [MICROSERVICE_ADMIN] FOR LOGIN [MICROSERVICE_ADMIN] WITH DEFAULT_SCHEMA=MICROSERVICE;

ALTER SERVER ROLE [sysadmin] ADD MEMBER [MICROSERVICE_ADMIN];

ALTER SERVER ROLE [securityadmin] ADD MEMBER [MICROSERVICE_ADMIN];

ALTER SERVER ROLE [serveradmin] ADD MEMBER [MICROSERVICE_ADMIN];

ALTER SERVER ROLE [setupadmin] ADD MEMBER [MICROSERVICE_ADMIN];

ALTER SERVER ROLE [processadmin] ADD MEMBER [MICROSERVICE_ADMIN];

ALTER SERVER ROLE [diskadmin] ADD MEMBER [MICROSERVICE_ADMIN];

ALTER SERVER ROLE [dbcreator] ADD MEMBER [MICROSERVICE_ADMIN];

ALTER SERVER ROLE [##MS_ServerStateReader##] ADD MEMBER [MICROSERVICE_ADMIN];

ALTER SERVER ROLE [##MS_ServerStateManager##] ADD MEMBER [MICROSERVICE_ADMIN];

ALTER SERVER ROLE [##MS_DefinitionReader##] ADD MEMBER [MICROSERVICE_ADMIN];

ALTER SERVER ROLE [##MS_DatabaseConnector##] ADD MEMBER [MICROSERVICE_ADMIN];

ALTER SERVER ROLE [##MS_DatabaseManager##] ADD MEMBER [MICROSERVICE_ADMIN];

ALTER SERVER ROLE [##MS_LoginManager##] ADD MEMBER [MICROSERVICE_ADMIN];

ALTER SERVER ROLE [##MS_SecurityDefinitionReader##] ADD MEMBER [MICROSERVICE_ADMIN];

ALTER SERVER ROLE [##MS_PerformanceDefinitionReader##] ADD MEMBER [MICROSERVICE_ADMIN];

ALTER SERVER ROLE [##MS_ServerSecurityStateReader##] ADD MEMBER [MICROSERVICE_ADMIN];

ALTER SERVER ROLE [##MS_ServerPerformanceStateReader##] ADD MEMBER [MICROSERVICE_ADMIN];

CREATE LOGIN [MICROSERVICE_ADMIN_PROXY1] WITH PASSWORD=N'p455w0Rd', DEFAULT_DATABASE=[master], DEFAULT_LANGUAGE=[us_english], CHECK_EXPIRATION=OFF, CHECK_POLICY=ON;

CREATE USER [MICROSERVICE_ADMIN_PROXY1] FOR LOGIN [MICROSERVICE_ADMIN_PROXY1] WITH DEFAULT_SCHEMA=MICROSERVICE;

ALTER SERVER ROLE [sysadmin] ADD MEMBER [MICROSERVICE_ADMIN_PROXY1];

ALTER SERVER ROLE [securityadmin] ADD MEMBER [MICROSERVICE_ADMIN_PROXY1];

ALTER SERVER ROLE [serveradmin] ADD MEMBER [MICROSERVICE_ADMIN_PROXY1];

ALTER SERVER ROLE [setupadmin] ADD MEMBER [MICROSERVICE_ADMIN_PROXY1];

ALTER SERVER ROLE [processadmin] ADD MEMBER [MICROSERVICE_ADMIN_PROXY1];

ALTER SERVER ROLE [diskadmin] ADD MEMBER [MICROSERVICE_ADMIN_PROXY1];

ALTER SERVER ROLE [dbcreator] ADD MEMBER [MICROSERVICE_ADMIN_PROXY1];

ALTER SERVER ROLE [##MS_ServerStateReader##] ADD MEMBER [MICROSERVICE_ADMIN_PROXY1];

ALTER SERVER ROLE [##MS_ServerStateManager##] ADD MEMBER [MICROSERVICE_ADMIN_PROXY1];

ALTER SERVER ROLE [##MS_DefinitionReader##] ADD MEMBER [MICROSERVICE_ADMIN_PROXY1];

ALTER SERVER ROLE [##MS_DatabaseConnector##] ADD MEMBER [MICROSERVICE_ADMIN_PROXY1];

ALTER SERVER ROLE [##MS_DatabaseManager##] ADD MEMBER [MICROSERVICE_ADMIN_PROXY1];

ALTER SERVER ROLE [##MS_LoginManager##] ADD MEMBER [MICROSERVICE_ADMIN_PROXY1];

ALTER SERVER ROLE [##MS_SecurityDefinitionReader##] ADD MEMBER [MICROSERVICE_ADMIN_PROXY1];

ALTER SERVER ROLE [##MS_PerformanceDefinitionReader##] ADD MEMBER [MICROSERVICE_ADMIN_PROXY1];

ALTER SERVER ROLE [##MS_ServerSecurityStateReader##] ADD MEMBER [MICROSERVICE_ADMIN_PROXY1];

ALTER SERVER ROLE [##MS_ServerPerformanceStateReader##] ADD MEMBER [MICROSERVICE_ADMIN_PROXY1];

CREATE LOGIN [MICROSERVICE_ADMIN_PROXY2] WITH PASSWORD=N'p455w0Rd', DEFAULT_DATABASE=[master], DEFAULT_LANGUAGE=[us_english], CHECK_EXPIRATION=OFF, CHECK_POLICY=ON;

CREATE USER [MICROSERVICE_ADMIN_PROXY2] FOR LOGIN [MICROSERVICE_ADMIN_PROXY2] WITH DEFAULT_SCHEMA=MICROSERVICE;

ALTER SERVER ROLE [sysadmin] ADD MEMBER [MICROSERVICE_ADMIN_PROXY2];

ALTER SERVER ROLE [securityadmin] ADD MEMBER [MICROSERVICE_ADMIN_PROXY2];

ALTER SERVER ROLE [serveradmin] ADD MEMBER [MICROSERVICE_ADMIN_PROXY2];

ALTER SERVER ROLE [setupadmin] ADD MEMBER [MICROSERVICE_ADMIN_PROXY2];

ALTER SERVER ROLE [processadmin] ADD MEMBER [MICROSERVICE_ADMIN_PROXY2];

ALTER SERVER ROLE [diskadmin] ADD MEMBER [MICROSERVICE_ADMIN_PROXY2];

ALTER SERVER ROLE [dbcreator] ADD MEMBER [MICROSERVICE_ADMIN_PROXY2];

ALTER SERVER ROLE [##MS_ServerStateReader##] ADD MEMBER [MICROSERVICE_ADMIN_PROXY2];

ALTER SERVER ROLE [##MS_ServerStateManager##] ADD MEMBER [MICROSERVICE_ADMIN_PROXY2];

ALTER SERVER ROLE [##MS_DefinitionReader##] ADD MEMBER [MICROSERVICE_ADMIN_PROXY2];

ALTER SERVER ROLE [##MS_DatabaseConnector##] ADD MEMBER [MICROSERVICE_ADMIN_PROXY2];

ALTER SERVER ROLE [##MS_DatabaseManager##] ADD MEMBER [MICROSERVICE_ADMIN_PROXY2];

ALTER SERVER ROLE [##MS_LoginManager##] ADD MEMBER [MICROSERVICE_ADMIN_PROXY2];

ALTER SERVER ROLE [##MS_SecurityDefinitionReader##] ADD MEMBER [MICROSERVICE_ADMIN_PROXY2];

ALTER SERVER ROLE [##MS_PerformanceDefinitionReader##] ADD MEMBER [MICROSERVICE_ADMIN_PROXY2];

ALTER SERVER ROLE [##MS_ServerSecurityStateReader##] ADD MEMBER [MICROSERVICE_ADMIN_PROXY2];

ALTER SERVER ROLE [##MS_ServerPerformanceStateReader##] ADD MEMBER [MICROSERVICE_ADMIN_PROXY2];

-- CREATE LOGIN [MICROSERVICE] WITH PASSWORD=N'p455w0Rd', DEFAULT_DATABASE=[master], DEFAULT_LANGUAGE=[us_english], CHECK_EXPIRATION=OFF, CHECK_POLICY=ON;
--
-- ALTER SERVER ROLE [sysadmin] ADD MEMBER [MICROSERVICE];
--
-- ALTER SERVER ROLE [setupadmin] ADD MEMBER [MICROSERVICE];
--
-- ALTER SERVER ROLE [##MS_ServerStateReader##] ADD MEMBER [MICROSERVICE];
--
-- ALTER SERVER ROLE [##MS_DefinitionReader##] ADD MEMBER [MICROSERVICE];
--
-- ALTER SERVER ROLE [##MS_DatabaseConnector##] ADD MEMBER [MICROSERVICE];
--
-- ALTER SERVER ROLE [##MS_SecurityDefinitionReader##] ADD MEMBER [MICROSERVICE];
--
-- ALTER SERVER ROLE [##MS_PerformanceDefinitionReader##] ADD MEMBER [MICROSERVICE];
--
-- ALTER SERVER ROLE [##MS_ServerSecurityStateReader##] ADD MEMBER [MICROSERVICE];
--
-- ALTER SERVER ROLE [##MS_ServerPerformanceStateReader##] ADD MEMBER [MICROSERVICE];

CREATE LOGIN [MICROSERVICE_PROXY1] WITH PASSWORD=N'p455w0Rd', DEFAULT_DATABASE=[master], DEFAULT_LANGUAGE=[us_english], CHECK_EXPIRATION=OFF, CHECK_POLICY=ON;

CREATE USER [MICROSERVICE_PROXY1] FOR LOGIN [MICROSERVICE_PROXY1] WITH DEFAULT_SCHEMA=MICROSERVICE;

ALTER SERVER ROLE [sysadmin] ADD MEMBER [MICROSERVICE_PROXY1];

ALTER SERVER ROLE [setupadmin] ADD MEMBER [MICROSERVICE_PROXY1];

ALTER SERVER ROLE [##MS_ServerStateReader##] ADD MEMBER [MICROSERVICE_PROXY1];

ALTER SERVER ROLE [##MS_DefinitionReader##] ADD MEMBER [MICROSERVICE_PROXY1];

ALTER SERVER ROLE [##MS_DatabaseConnector##] ADD MEMBER [MICROSERVICE_PROXY1];

ALTER SERVER ROLE [##MS_SecurityDefinitionReader##] ADD MEMBER [MICROSERVICE_PROXY1];

ALTER SERVER ROLE [##MS_PerformanceDefinitionReader##] ADD MEMBER [MICROSERVICE_PROXY1];

ALTER SERVER ROLE [##MS_ServerSecurityStateReader##] ADD MEMBER [MICROSERVICE_PROXY1];

ALTER SERVER ROLE [##MS_ServerPerformanceStateReader##] ADD MEMBER [MICROSERVICE_PROXY1];

CREATE LOGIN [MICROSERVICE_PROXY2] WITH PASSWORD=N'p455w0Rd', DEFAULT_DATABASE=[master], DEFAULT_LANGUAGE=[us_english], CHECK_EXPIRATION=OFF, CHECK_POLICY=ON;

CREATE USER [MICROSERVICE_PROXY2] FOR LOGIN [MICROSERVICE_PROXY2] WITH DEFAULT_SCHEMA=MICROSERVICE;

ALTER SERVER ROLE [sysadmin] ADD MEMBER [MICROSERVICE_PROXY2];

ALTER SERVER ROLE [setupadmin] ADD MEMBER [MICROSERVICE_PROXY2];

ALTER SERVER ROLE [##MS_ServerStateReader##] ADD MEMBER [MICROSERVICE_PROXY2];

ALTER SERVER ROLE [##MS_DefinitionReader##] ADD MEMBER [MICROSERVICE_PROXY2];

ALTER SERVER ROLE [##MS_DatabaseConnector##] ADD MEMBER [MICROSERVICE_PROXY2];

ALTER SERVER ROLE [##MS_SecurityDefinitionReader##] ADD MEMBER [MICROSERVICE_PROXY2];

ALTER SERVER ROLE [##MS_PerformanceDefinitionReader##] ADD MEMBER [MICROSERVICE_PROXY2];

ALTER SERVER ROLE [##MS_ServerSecurityStateReader##] ADD MEMBER [MICROSERVICE_PROXY2];

ALTER SERVER ROLE [##MS_ServerPerformanceStateReader##] ADD MEMBER [MICROSERVICE_PROXY2];

CREATE LOGIN [MICROSERVICE_READER] WITH PASSWORD=N'p455w0Rd', DEFAULT_DATABASE=[master], DEFAULT_LANGUAGE=[us_english], CHECK_EXPIRATION=OFF, CHECK_POLICY=ON;

CREATE USER [MICROSERVICE_READER] FOR LOGIN [MICROSERVICE_READER] WITH DEFAULT_SCHEMA=MICROSERVICE;

ALTER SERVER ROLE [##MS_ServerStateReader##] ADD MEMBER [MICROSERVICE_READER];

ALTER SERVER ROLE [##MS_DefinitionReader##] ADD MEMBER [MICROSERVICE_READER];

ALTER SERVER ROLE [##MS_DatabaseConnector##] ADD MEMBER [MICROSERVICE_READER];

ALTER SERVER ROLE [##MS_SecurityDefinitionReader##] ADD MEMBER [MICROSERVICE_READER];

ALTER SERVER ROLE [##MS_PerformanceDefinitionReader##] ADD MEMBER [MICROSERVICE_READER];

ALTER SERVER ROLE [##MS_ServerSecurityStateReader##] ADD MEMBER [MICROSERVICE_READER];

ALTER SERVER ROLE [##MS_ServerPerformanceStateReader##] ADD MEMBER [MICROSERVICE_READER];

CREATE SCHEMA [MICROSERVICE];

ALTER USER [MICROSERVICE_ADMIN] WITH DEFAULT_SCHEMA = MICROSERVICE;
ALTER USER [MICROSERVICE_ADMIN_PROXY1] WITH DEFAULT_SCHEMA = MICROSERVICE;
ALTER USER [MICROSERVICE_ADMIN_PROXY2] WITH DEFAULT_SCHEMA = MICROSERVICE;
-- ALTER USER [MICROSERVICE] WITH DEFAULT_SCHEMA = MICROSERVICE;
ALTER USER [MICROSERVICE_PROXY1] WITH DEFAULT_SCHEMA = MICROSERVICE;
ALTER USER [MICROSERVICE_PROXY2] WITH DEFAULT_SCHEMA = MICROSERVICE;
ALTER USER [MICROSERVICE_READER] WITH DEFAULT_SCHEMA = MICROSERVICE;