DELETE FROM MICROSERVICE.FLOOR_DESKS
DROP TABLE MICROSERVICE.FLOOR_DESKS

DELETE FROM MICROSERVICE.DESKS
DROP TABLE MICROSERVICE.DESKS

DELETE FROM MICROSERVICE.BUILDING_FLOORS
DROP TABLE MICROSERVICE.BUILDING_FLOORS

DELETE FROM MICROSERVICE.FLOORS
DROP TABLE MICROSERVICE.FLOORS

DELETE FROM MICROSERVICE.BUILDINGS
DROP TABLE MICROSERVICE.BUILDINGS